FROM tensorflow/tensorflow:1.14.0-gpu-py3

RUN pip3 install ipyvolume vaex keras matplotlib scikit-learn pandas
RUN pip3 install bokeh
RUN pip3 install comet_ml
RUN pip3 install pydot
RUN apt-get install -y graphviz